# Generated by Django 5.2.7 on 2025-10-09 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        ('platillos', '0002_platillo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='ordenes.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.orden')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='platillos.platillo')),
            ],
        ),
    ]
