# Generated by Django 5.2.7 on 2025-10-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_orden_ordendetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estatus',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
